### ISSUE TITLE
Error running the app.py file

### ISSUE THREAD

**Issue by sushantsur23** [krishnaik06/Car-Price-Prediction#6]
![image](https://user-images.githubusercontent.com/77981264/110789029-6ddefb80-8295-11eb-982e-c568bbfd62ae.png)

![image](https://user-images.githubusercontent.com/77981264/110789100-83542580-8295-11eb-988d-769d1d581bcc.png)

I m getting this error message any idea on how to resolve this?

**Comment by jibin-sebastian** [comment]
please try with the below code

model = open('random_forest_regression_model.pkl', 'wb')
pickle.dump(dict, model)
model.close()

**Comment by Prasad20031218** [comment]
yes I'm also having problem in running app.py can anyone please resolve this?

**Comment by noe2019** [comment]
Hi Kris!
I am having the following issue in my attempts.

Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask, render_template, request
  File "/opt/anaconda3/envs/geo-python-student/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/opt/anaconda3/envs/geo-python-student/lib/python3.8/site-packages/jinja2/__init__.py)

**Comment by jibin-sebastian** [comment]
please try with the below code

model = open('random_forest_regression_model.pkl', 'wb')
pickle.dump(dict, model)
model.close(
